import { useState, useEffect, useContext, useRef } from 'react'
import { ToastContext } from '../App'
import {
    FileText, Upload, BrainCircuit, Plus, Building2,
    MapPin, BarChart2, Pause, Play, Trash2, Pencil,
    FolderOpen, Paperclip, X
} from 'lucide-react'

export default function JDManager() {
    const { addToast, API } = useContext(ToastContext)
    const [jds, setJds] = useState([])
    const [loading, setLoading] = useState(true)
    const [showModal, setShowModal] = useState(false)
    const [showGenModal, setShowGenModal] = useState(false)
    const [showUploadModal, setShowUploadModal] = useState(false)
    const [generating, setGenerating] = useState(false)
    const [uploading, setUploading] = useState(false)
    const [editJd, setEditJd] = useState(null)
    const fileRef = useRef()

    const [form, setForm] = useState({
        title: '', department: 'Engineering', location: 'Remote',
        employment_type: 'Full-time', experience_level: 'Mid-level',
        salary_range: '', description: '', requirements: '', nice_to_have: '',
    })
    const [genForm, setGenForm] = useState({ title: '', department: 'Engineering', brief: '', experience_level: 'Mid-level' })
    const [uploadFiles, setUploadFiles] = useState([])

    useEffect(() => { loadJDs() }, [])

    async function loadJDs() {
        try {
            const res = await fetch(`${API}/api/jds`)
            setJds(await res.json())
        } catch (err) { console.error(err) }
        finally { setLoading(false) }
    }

    function openCreate() {
        setEditJd(null)
        setForm({ title: '', department: 'Engineering', location: 'Remote', employment_type: 'Full-time', experience_level: 'Mid-level', salary_range: '', description: '', requirements: '', nice_to_have: '' })
        setShowModal(true)
    }

    function openEdit(jd) {
        setEditJd(jd)
        setForm({ title: jd.title, department: jd.department, location: jd.location, employment_type: jd.employment_type, experience_level: jd.experience_level, salary_range: jd.salary_range, description: jd.description, requirements: jd.requirements, nice_to_have: jd.nice_to_have })
        setShowModal(true)
    }

    async function handleSubmit(e) {
        e.preventDefault()
        try {
            const url = editJd ? `${API}/api/jds/${editJd.id}` : `${API}/api/jds`
            const method = editJd ? 'PUT' : 'POST'
            const res = await fetch(url, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) })
            const data = await res.json()
            addToast(data.message || 'JD saved successfully!', 'success')
            setShowModal(false)
            loadJDs()
        } catch (err) { addToast('Failed to save JD', 'error') }
    }

    async function handleGenerate(e) {
        e.preventDefault()
        setGenerating(true)
        try {
            const res = await fetch(`${API}/api/jds/generate`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(genForm) })
            const data = await res.json()
            addToast(data.message || 'JD generated by AI!', 'success')
            setShowGenModal(false)
            setGenForm({ title: '', department: 'Engineering', brief: '', experience_level: 'Mid-level' })
            loadJDs()
        } catch (err) { addToast('Failed to generate JD', 'error') }
        finally { setGenerating(false) }
    }

    async function handleUploadJDs(e) {
        e.preventDefault()
        if (!uploadFiles.length) return addToast('Please select JD files', 'error')
        setUploading(true)
        let successCount = 0

        for (const file of uploadFiles) {
            try {
                const formData = new FormData()
                formData.append('file', file)
                const res = await fetch(`${API}/api/jds/upload`, { method: 'POST', body: formData })
                if (res.ok) successCount++
                else addToast(`Failed to upload ${file.name}`, 'error')
            } catch (err) {
                addToast(`Error uploading ${file.name}`, 'error')
            }
        }

        if (successCount > 0) {
            addToast(`${successCount} JD(s) uploaded successfully!`, 'success')
            loadJDs()
        }
        setUploading(false)
        setUploadFiles([])
        setShowUploadModal(false)
    }

    async function deleteJD(id, title) {
        if (!confirm(`Delete "${title}" and all its candidates?`)) return
        try {
            await fetch(`${API}/api/jds/${id}`, { method: 'DELETE' })
            addToast(`"${title}" deleted`, 'success')
            loadJDs()
        } catch (err) { addToast('Failed to delete', 'error') }
    }

    async function toggleStatus(jd) {
        const newStatus = jd.status === 'active' ? 'paused' : 'active'
        try {
            await fetch(`${API}/api/jds/${jd.id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: newStatus }) })
            addToast(`JD ${newStatus === 'active' ? 'activated' : 'paused'}`, 'success')
            loadJDs()
        } catch (err) { addToast('Failed to update status', 'error') }
    }

    return (
        <div className="animate-fade-in">
            <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 12 }}>
                <div>
                    <h2><FileText size={24} style={{ verticalAlign: 'middle', marginRight: 8 }} />Job Descriptions</h2>
                    <p>Create, upload, or let AI craft the perfect JD for you</p>
                </div>
                <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
                    <button className="btn btn-secondary" onClick={() => setShowUploadModal(true)}>
                        <Upload size={16} /> Upload Files
                    </button>
                    <button className="btn btn-secondary" onClick={() => setShowGenModal(true)}>
                        <BrainCircuit size={16} /> AI Generate
                    </button>
                    <button className="btn btn-primary" onClick={openCreate}>
                        <Plus size={16} /> Create JD
                    </button>
                </div>
            </div>

            {loading ? (
                <div className="jd-grid">
                    {[1, 2, 3].map(i => (
                        <div key={i} className="card">
                            <div className="loading-skeleton loading-bar medium" />
                            <div className="loading-skeleton loading-bar long" />
                            <div className="loading-skeleton loading-bar short" />
                        </div>
                    ))}
                </div>
            ) : jds.length === 0 ? (
                <div className="card">
                    <div className="empty-state">
                        <div className="empty-icon"><FileText size={40} /></div>
                        <h3>No job descriptions yet</h3>
                        <p>Create your first JD to start screening candidates</p>
                        <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
                            <button className="btn btn-secondary" onClick={() => setShowUploadModal(true)}>
                                <Upload size={16} /> Upload Files
                            </button>
                            <button className="btn btn-secondary" onClick={() => setShowGenModal(true)}>
                                <BrainCircuit size={16} /> AI Generate
                            </button>
                            <button className="btn btn-primary" onClick={openCreate}>
                                <Pencil size={16} /> Create Manually
                            </button>
                        </div>
                    </div>
                </div>
            ) : (
                <div className="jd-grid">
                    {jds.map(jd => (
                        <div key={jd.id} className="jd-card" onClick={() => openEdit(jd)}>
                            <div className={`jd-status-dot ${jd.status}`} title={jd.status} />
                            <h3>{jd.title}</h3>
                            <div className="jd-meta">
                                <span><Building2 size={13} /> {jd.department}</span>
                                <span><MapPin size={13} /> {jd.location}</span>
                                <span><BarChart2 size={13} /> {jd.experience_level}</span>
                            </div>
                            <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: 16, lineHeight: 1.6, display: '-webkit-box', WebkitLineClamp: 3, WebkitBoxOrient: 'vertical', overflow: 'hidden' }}>
                                {jd.description}
                            </p>
                            <div className="jd-stats">
                                <div className="jd-stat">
                                    <div className="jd-stat-value">{jd.candidate_count}</div>
                                    <div className="jd-stat-label">Candidates</div>
                                </div>
                                <div className="jd-stat">
                                    <div className="jd-stat-value">{jd.shortlisted_count}</div>
                                    <div className="jd-stat-label">Shortlisted</div>
                                </div>
                                <div className="jd-stat">
                                    <div className="jd-stat-value">{jd.avg_score}%</div>
                                    <div className="jd-stat-label">Avg Score</div>
                                </div>
                            </div>
                            <div style={{ display: 'flex', gap: 8, marginTop: 16 }} onClick={e => e.stopPropagation()}>
                                <button className="btn btn-sm btn-secondary" onClick={() => toggleStatus(jd)}>
                                    {jd.status === 'active' ? <><Pause size={14} /> Pause</> : <><Play size={14} /> Activate</>}
                                </button>
                                <button className="btn btn-sm btn-danger" onClick={() => deleteJD(jd.id, jd.title)}>
                                    <Trash2 size={14} />
                                </button>
                            </div>
                        </div>
                    ))}
                </div>
            )}

            {/* Create/Edit Modal */}
            {showModal && (
                <div className="modal-overlay" onClick={() => setShowModal(false)}>
                    <div className="modal modal-lg" onClick={e => e.stopPropagation()}>
                        <div className="modal-header">
                            <h3>{editJd ? <><Pencil size={18} style={{ verticalAlign: 'middle', marginRight: 6 }} />Edit Job Description</> : <><FileText size={18} style={{ verticalAlign: 'middle', marginRight: 6 }} />New Job Description</>}</h3>
                            <button className="modal-close" onClick={() => setShowModal(false)}><X size={16} /></button>
                        </div>
                        <form onSubmit={handleSubmit}>
                            <div className="form-row">
                                <div className="form-group">
                                    <label>Job Title *</label>
                                    <input className="form-input" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} placeholder="e.g. Senior React Developer" required />
                                </div>
                                <div className="form-group">
                                    <label>Department</label>
                                    <input className="form-input" value={form.department} onChange={e => setForm({ ...form, department: e.target.value })} placeholder="Engineering" />
                                </div>
                            </div>
                            <div className="form-row">
                                <div className="form-group">
                                    <label>Location</label>
                                    <input className="form-input" value={form.location} onChange={e => setForm({ ...form, location: e.target.value })} placeholder="Remote / Hyderabad" />
                                </div>
                                <div className="form-group">
                                    <label>Employment Type</label>
                                    <select className="form-select" value={form.employment_type} onChange={e => setForm({ ...form, employment_type: e.target.value })}>
                                        <option>Full-time</option><option>Part-time</option><option>Contract</option><option>Internship</option>
                                    </select>
                                </div>
                            </div>
                            <div className="form-row">
                                <div className="form-group">
                                    <label>Experience Level</label>
                                    <select className="form-select" value={form.experience_level} onChange={e => setForm({ ...form, experience_level: e.target.value })}>
                                        <option>Entry-level</option><option>Mid-level</option><option>Senior</option><option>Lead</option><option>Principal</option>
                                    </select>
                                </div>
                                <div className="form-group">
                                    <label>Salary Range</label>
                                    <input className="form-input" value={form.salary_range} onChange={e => setForm({ ...form, salary_range: e.target.value })} placeholder="e.g. 8-15 LPA" />
                                </div>
                            </div>
                            <div className="form-group">
                                <label>Description *</label>
                                <textarea className="form-textarea" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} placeholder="Describe the role, responsibilities, and team..." required />
                            </div>
                            <div className="form-group">
                                <label>Requirements</label>
                                <textarea className="form-textarea" value={form.requirements} onChange={e => setForm({ ...form, requirements: e.target.value })} placeholder="List the must-have skills and qualifications..." style={{ minHeight: 100 }} />
                            </div>
                            <div className="form-group">
                                <label>Nice to Have</label>
                                <textarea className="form-textarea" value={form.nice_to_have} onChange={e => setForm({ ...form, nice_to_have: e.target.value })} placeholder="Bonus skills that would be great..." style={{ minHeight: 80 }} />
                            </div>
                            <div className="modal-footer">
                                <button type="button" className="btn btn-secondary" onClick={() => setShowModal(false)}>Cancel</button>
                                <button type="submit" className="btn btn-primary">{editJd ? 'Update' : 'Create JD'}</button>
                            </div>
                        </form>
                    </div>
                </div>
            )}

            {/* AI Generate Modal */}
            {showGenModal && (
                <div className="modal-overlay" onClick={() => setShowGenModal(false)}>
                    <div className="modal" onClick={e => e.stopPropagation()}>
                        <div className="modal-header">
                            <h3><BrainCircuit size={18} style={{ verticalAlign: 'middle', marginRight: 6 }} />AI JD Generator</h3>
                            <button className="modal-close" onClick={() => setShowGenModal(false)}><X size={16} /></button>
                        </div>
                        <p style={{ color: 'var(--text-muted)', marginBottom: 20 }}>
                            Just tell me the role and a brief — I'll craft a professional JD in seconds!
                        </p>
                        <form onSubmit={handleGenerate}>
                            <div className="form-group">
                                <label>Job Title *</label>
                                <input className="form-input" value={genForm.title} onChange={e => setGenForm({ ...genForm, title: e.target.value })} placeholder="e.g. Full-Stack Developer" required />
                            </div>
                            <div className="form-row">
                                <div className="form-group">
                                    <label>Department</label>
                                    <input className="form-input" value={genForm.department} onChange={e => setGenForm({ ...genForm, department: e.target.value })} />
                                </div>
                                <div className="form-group">
                                    <label>Experience Level</label>
                                    <select className="form-select" value={genForm.experience_level} onChange={e => setGenForm({ ...genForm, experience_level: e.target.value })}>
                                        <option>Entry-level</option><option>Mid-level</option><option>Senior</option><option>Lead</option>
                                    </select>
                                </div>
                            </div>
                            <div className="form-group">
                                <label>Brief Description *</label>
                                <textarea className="form-textarea" value={genForm.brief} onChange={e => setGenForm({ ...genForm, brief: e.target.value })} placeholder="Describe what this person will do..." required />
                            </div>
                            <div className="modal-footer">
                                <button type="button" className="btn btn-secondary" onClick={() => setShowGenModal(false)}>Cancel</button>
                                <button type="submit" className="btn btn-primary" disabled={generating}>
                                    {generating ? <><span className="spinner" /> Generating...</> : <><BrainCircuit size={16} /> Generate JD</>}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}

            {/* Upload JD Files Modal */}
            {showUploadModal && (
                <div className="modal-overlay" onClick={() => setShowUploadModal(false)}>
                    <div className="modal" onClick={e => e.stopPropagation()}>
                        <div className="modal-header">
                            <h3><Upload size={18} style={{ verticalAlign: 'middle', marginRight: 6 }} />Upload JD Files</h3>
                            <button className="modal-close" onClick={() => setShowUploadModal(false)}><X size={16} /></button>
                        </div>
                        <p style={{ color: 'var(--text-muted)', marginBottom: 20 }}>
                            Upload your existing JD files (PDF, DOCX, or TXT). We'll extract the content and create JDs from them automatically!
                        </p>
                        <form onSubmit={handleUploadJDs}>
                            <div
                                className="dropzone"
                                onClick={() => fileRef.current?.click()}
                            >
                                <div className="dropzone-icon"><FolderOpen size={40} /></div>
                                <h3>Click to browse JD files</h3>
                                <p>Supports PDF, DOCX, and TXT files • Select multiple</p>
                            </div>
                            <input
                                ref={fileRef}
                                type="file"
                                accept=".pdf,.docx,.txt"
                                multiple
                                style={{ display: 'none' }}
                                onChange={e => setUploadFiles(Array.from(e.target.files))}
                            />

                            {uploadFiles.length > 0 && (
                                <div className="file-list" style={{ marginTop: 16 }}>
                                    {uploadFiles.map((f, i) => (
                                        <div key={i} className="file-item">
                                            <span className="file-name"><Paperclip size={14} style={{ verticalAlign: 'middle', marginRight: 6 }} />{f.name}</span>
                                            <button type="button" className="btn-icon" onClick={() => setUploadFiles(prev => prev.filter((_, idx) => idx !== i))}>
                                                <X size={14} />
                                            </button>
                                        </div>
                                    ))}
                                </div>
                            )}

                            <div className="modal-footer">
                                <button type="button" className="btn btn-secondary" onClick={() => setShowUploadModal(false)}>Cancel</button>
                                <button type="submit" className="btn btn-primary" disabled={uploading || !uploadFiles.length}>
                                    {uploading ? <><span className="spinner" /> Uploading...</> : <><Upload size={16} /> Upload {uploadFiles.length} File(s)</>}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    )
}
